
dataset:
  root: /mnt/hdd/combined_uav/
  num_workers: 32
  batch_size: 24
  image_size:
  - 512
  - 512
trainer:
  pretrained_path: checkpoints
  epochs: 50
  optimizer: AdamW
  loss_fn: DiceLoss
  lr: 0.0001
  gpu_id: 2
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.15
    patience: 10
    cooldown: 5
  early_stop:
    patience: 10
    min_delta: 0.001
    mode: min
  checkpoint:
    save_dir: checkpoints/unet
model:
  name: unet
